In [1]:
import pandas as pd

In [2]:
pd.read_parquet('../data/predictions/alphafold3_summary_confidences.parquet').head(2).transpose()

,0,1
name,00057fce464a9de2ec699af7e721648b272b078a,00057fce464a9de2ec699af7e721648b272b078a
seed,4,4
sample,0,1
ranking_score,0.326816,0.320315
fraction_disordered,0.02,0.02
has_clash,0.0,0.0
iptm,0.3,0.29
ptm,0.39,0.39
chain_iptm,"[0.1, 0.18, 0.09, 0.17, 0.08, 0.09, 0.08, 0.09...","[0.1, 0.18, 0.08, 0.16, 0.07, 0.1, 0.08, 0.09,..."
chain_pair_iptm,"[[0.16, 0.17, 0.09, 0.15, 0.06, 0.07, 0.06, 0....","[[0.16, 0.17, 0.07, 0.15, 0.05, 0.07, 0.06, 0...."
chain_pair_pae_min,"[[0.76, 29.74, 26.31, 30.63, 30.44, 30.67, 30....","[[0.76, 30.09, 30.67, 31.31, 31.47, 30.39, 31...."
chain_ptm,"[0.16, 0.35, 0.62, 0.56, 0.3, 0.56, 0.25, 0.72...","[0.16, 0.35, 0.61, 0.57, 0.33, 0.55, 0.26, 0.7..."
summary_confidences_path,00057fce464a9de2ec699af7e721648b272b078a/seed-...,00057fce464a9de2ec699af7e721648b272b078a/seed-...
predictions_path,25.12/daint-gh200/alphafold3_predictions/00057...,25.12/daint-gh200/alphafold3_predictions/00057...
batch_id,25.12/daint-gh200,25.12/daint-gh200
pool_id,p06843_p0cx63_p35691_p40064_p57744_q00723_q040...,p06843_p0cx63_p35691_p40064_p57744_q00723_q040...
pool_size,5090,5090
path,25.12/daint-gh200/alphafold3_predictions/00057...,25.12/daint-gh200/alphafold3_predictions/00057...
source,all,all
gpu,gh200,gh200
num_recycles,10,10
container,v3.0.1-daint1,v3.0.1-daint1

In [3]:
pd.read_parquet('../data/predictions/alphafold3_summary_pairs.parquet').head(2).transpose()

,0,1
name,0000e33a0eab4a1d137c732ccacef998d3b1b2cd,0000e33a0eab4a1d137c732ccacef998d3b1b2cd
batch_id,26.02/euler-std-a100-r3,26.02/euler-std-a100-r3
chain_pair_iptm_best,0.15,0.11
chain_pair_iptm_mean,0.15,0.11
af3_pair,p31382_p34110,p31382_p40580
af3_id1,p31382,p31382
af3_id2,p34110,p40580
seq_len1,759,759
seq_len2,944,263
pair_len,1703,1022
string_protein1,,
string_protein2,,
string_neighborhood,0,0
string_fusion,0,0
string_cooccurence,0,0
string_coexpression,0,0
string_experimental,0,0
string_database,0,0
string_textmining,0,0
string_combined_score,0,0
physical_protein1,,
physical_protein2,,
physical_homology,0,0
physical_experiments,0,0
physical_experiments_transferred,0,0
physical_database,0,0
physical_database_transferred,0,0
physical_textmining,0,0
physical_textmining_transferred,0,0
physical_combined_score,0,0
Michaelis2023_source,,
Michaelis2023_target,,
Michaelis2023_hit,False,False
chain_pair_iptm_best_corrected,0.005457,0.006815
chain_pair_iptm_mean_corrected,0.005171,0.006561